### PR TITLE
I Want to `sandbox`! ... again

### PR DESCRIPTION
**Pull request by Malvoz**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@aarongustafson, should we accept "wants" outright, or would it be appropriate to discuss if some other part of the platform could meet this need.... for example, we could evaluate if the Feature Policy API could address this use case?

**Comment by aarongustafson** [comment]
@marcoscaceres My feeling was that some submissions may require a bit of back & forth between the submitter and us to clarify the underlying problem. If there’s an existing path, we can inform them of that and it probably would not make sense to include that “want” in the site. If it is a well-articulated need, however, without a clear pre-existing solution, it can be added (perhaps with some editorial refinement).

In the case of @Malvoz’s submission, I bow to your knowledge of Feature Policy. If it already provides the means of doing this, awesome. If not, but you think that’s the right area for managing this request, let’s propose a rewrite of the “want” that specifically scopes the sandboxing control desire within the context of Feature Policies.

Does that make sense?

**Comment by Malvoz** [comment]
> we could evaluate if the Feature Policy API could address this use case?

This https://github.com/w3c/webappsec-feature-policy/issues/300 does discuss an opt-in negotiation, perhaps `Require-Sandbox-Policy`.

But looking at the bigger picture, even allowing/disallowing some features for FP itself may be just as tricky as with `sandbox`. I think, either way: having an opt-in negotiation mechanism, or just having code distributors providing proper documentation for what's necessary to allow for a fully interoperable embedment, the challenge may very well be motivating them to do so.

**Comment by Malvoz** [comment]
Perhaps [FP reporting](https://github.com/w3c/webappsec-feature-policy/blob/master/reporting.md) could go a long way, it'd still allow for content to first break and then (sandbox) features can be adjusted accordingly.

Anyhow, my Want isn't explicitly asking for a technology to achieve API/feature advertisement. It may be more reliable having code distributors to advertise required features in their documentation, but I suppose there's little motivation for it as nobody seems to be doing that.

**Pull request merged**
