### PR TITLE
I Want to `sandbox`!

### PR DESCRIPTION
**Pull request by Malvoz**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Any reason why 2 is deleted? Don't want that anymore?

**Comment by Malvoz** [comment]
We're not deleting that!

**Comment by Malvoz** [comment]
Sorry about that, I'm tired... See https://github.com/WebWeWant/webwewant.fyi/pull/5

**Comment by marcoscaceres** [comment]
No problem:) just making sure. Thanks for resending! Have a rest 🛌

**Pull request closed without merging**
