### PR TITLE
Update voting.md

### PR DESCRIPTION
**Pull request by guest271314**

### CODE REVIEW

**Comment by guest271314** [comment]
https://github.com/WebWeWant/webwewant.fyi/pull/15/commits/92d8fb9faab27031c1c56b365bd960bcc9db3f2d and https://github.com/WebWeWant/webwewant.fyi/pull/15/commits/3d73df0be65166edbd758aa68572f98239170403 should not be included in this PR only https://github.com/WebWeWant/webwewant.fyi/pull/15/commits/b967523b3d6534580ceb35787bc06e11d1bdd726. Substitutes "alter" for "ater" at https://webwewant.fyi/voting/. Should this PR be closed, forked branches deleted, refiled without the former two commits?

**Comment by aarongustafson** [comment]
Nope, it’s good. Thank you!

**Comment by guest271314** [comment]
@aarongustafson BTW, the "voting" mechanism is not immediately clear. Why is "voting" necessary at all? What does a "vote" objectively mean relevant to the "want"? The Web We Want does not need to store user data if you still have the concept that a "vote" has some value re the site. 

Will more than likely file an issue to describe precisely what mean.

**Comment by aarongustafson** [comment]
I made a few updates to [the "voting" page](https://webwewant.fyi/voting/). Let me know if that takes care of clarifying things.

**Comment by guest271314** [comment]
Why cannot the site use a `<button>+1</button>` on each page count and display clicks on the button? Very simple. No attribution for click "vote". No social experimentation.

**Comment by aarongustafson** [comment]
I’m not averse to it, but we don’t have a backend (and I’d rather not create one). Do you have thoughts on how that could be accomplished?

**Comment by guest271314** [comment]
If there is no backend how does 

> will take vote tallies

occur at all per the current language of "voting.md"?

You can use this GitHub repository. File an issue with each comment being the "want" from the .fyi site. Count the +1's for each comment.

**Comment by guest271314** [comment]
> I made a few updates to [the "voting" page](https://webwewant.fyi/voting/). Let me know if that takes care of clarifying things.

No. Either the vote means everything or the vote means nothing. "will take vote tallies into account" is akin to an electoral college blackbox. "account" for exactly what? Meaning the interpreter of the "vote" can take any vote "into account" yet ignore the vote at their own discretion. 

Again, why is any "vote" needed at all? Since "The browser vendors and standards bodies" do what they please anyway, with any proposal and/or arbitrarily why would that not be the case with "The Web We Want".

Are "webmentions", "bookmark" and "like" links related to the initial sentence "If you build websites, you inevitably run into problems. Maybe there’s no way to achieve an aspect of your design"?

**Comment by guest271314** [comment]
From perspective here the criteria should be the first and second sentence at "Home" meaning if a single or more than one "want" is "selcted" for further consideration that consideration should be based on the difficulty of achieving the expected output, both at all, and by way of possible workarounds. What is or are the most technically challenging and difficult to achieve "want" irrespective of any "vote" or [Popularity](https://brendaneich.com/2008/04/popularity/). 

If a "vote" must be done, and the criteria is number of votes for some form of "selection" one other alternative would be to create branch in the repository for each "want" and count the forks over a given span of time, for example, 30 days.

**Comment by guest271314** [comment]
Will this vote @dsanders11 https://webwewant.fyi/wants/7/ be reflected on the page at Votes: N?

**Comment by aarongustafson** [comment]
It should. Making sure Brid.gy has access to the project now…

**Comment by aarongustafson** [comment]
Looks like it shows up. Should be collected in the next hourly build. https://webmention.io/api/mentions.jf2?target=https://webwewant.fyi/wants/7/&token=bUYdf3WnNBc0-i6cq47EXw

**Pull request merged**
